### PR TITLE
Feat/update selfkey ui material ui

### PR DESCRIPTION
**Pull request by andregoncalves**

### CODE REVIEW

**Comment by designhorf** [comment]
After that PR (https://github.com/SelfKeyFoundation/selfkey-ui/pull/200) will be merged, need to update this branch with latest SK UI.

**Comment by designhorf** [comment]
@andregoncalves did you have a chance to look at the SK Profile `add document` and  `add information` popups?

**Comment by andregoncalves** [comment]
Yes, I will take look today.

**Comment by andregoncalves** [comment]
Seeems to be caused by a mismatch with selfkey-ui version between wallet and jsonschema-material-ui.

**Comment by sk91** [comment]
@andre need to update https://github.com/SelfKeyFoundation/react-jsonschema-form-material-theme/pull/50 hash after it is merged

**Comment by andregoncalves** [comment]
@designhorf can you check if this is ready now to merge to dev for extended QA?

**Comment by designhorf** [comment]
@andregoncalves now it's ready

**Pull request merged**
