### PR TITLE
fix(manage-applications): hotfix on update flow

### PR DESCRIPTION
**Pull request by eduardosmoura**

### CODE REVIEW

**Comment by andregoncalves** [comment]
@eduardosmoura is this work in progress?

**Comment by eduardosmoura** [comment]
@andregoncalves no, this is a final fix, but it was an easy change.

**Comment by andregoncalves** [comment]
Can you fix the merge conflicts?

**Comment by eduardosmoura** [comment]
Yes, sure @andregoncalves.

**Comment by eduardosmoura** [comment]
It's done @andregoncalves.

**Pull request merged**
