### PR TITLE
fix(eslint): fix eslint in project

### PR DESCRIPTION
**Pull request by sk91**

### CODE REVIEW

**Comment by sk91** [comment]
@dfcowell I really underestimated this "quick" task

**Comment by dfcowell** [comment]
@sk91 heh I thought it would take a bit longer than you anticipated. :)

This is pretty low priority now compared to any bugs that come through, but keep working on it when you have spare time.

**Comment by sk91** [comment]
@dfcowell @rodrigopavezi 
All lint related tests pass now

**Comment by dfcowell** [comment]
@sk91 this will be good to go once you fix the conflict. 👍

**Pull request merged**
