### PR TITLE
feat: support for kyc application status actions

### PR DESCRIPTION
**Pull request by andregoncalves**
Support for handling KYC application status and redirecting accordingly.

### CODE REVIEW

**Comment by andregoncalves** [comment]
@designhorf is working on this branch to fix UI issues with the different button states.

**Comment by designhorf** [comment]
@andregoncalves @rodrigopavezi UI changes are done, ready for review

**Comment by designhorf** [comment]
need to update Selfkey UI, there was a small change. I'm working on it

**Comment by andregoncalves** [comment]
Great work @designhorf 💯

**Pull request merged**
