### PR TITLE
feat(corp1): ui add create entity button to menu

### PR DESCRIPTION
**Pull request by eduardosmoura**

### CODE REVIEW

**Comment by andregoncalves** [comment]
@eduardosmoura please check conflicts.

**Comment by eduardosmoura** [comment]
@andregoncalves conflicts solved. Sorry about the delay.

**Comment by andregoncalves** [comment]
@eduardosmoura unit tests seem to be failing, can you check?

**Comment by eduardosmoura** [comment]
Will do @andregoncalves

**Pull request merged**
